name: VPS + Puppeteer
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build Environment
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip fonts-liberation libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libxrandr2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libxss1 libgbm1 xdg-utils git curl
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install puppeteer-real-browser hpack
          git clone https://github.com/depchaiaiyeu/dos-bot
          cd dos-bot
      - name: Setup tmate
        run: |
          curl -fsSL https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz | tar -xJ
          chmod +x tmate-2.4.0-static-linux-amd64/tmate
          ./tmate-2.4.0-static-linux-amd64/tmate -S /tmp/tmate new-session -d "bash"
          sleep 8
          SSH_LINK=$(./tmate-2.4.0-static-linux-amd64/tmate -S /tmp/tmate display -p '#{tmate_ssh}')
          WEB_LINK=$(./tmate-2.4.0-static-linux-amd64/tmate -S /tmp/tmate display -p '#{tmate_web}')
          echo "VPS ready!"
          echo "SSH: $SSH_LINK"
          echo "Web: $WEB_LINK"
      - name: Keep alive
        run: |
          echo "VPS running for 1 hour"
          sleep 3600
